benchmark/apis/hcaptcha/__init__.py
from .routes import hcaptcha

benchmark/apis/hcaptcha/routes.py
import os
import json

from flask import Blueprint, render_template, jsonify, request


challenges_path = os.path.join(os.path.dirname(__file__), "challenges.json")
challenges_file = open(challenges_path)
challenges_dict: dict = json.load(challenges_file)
challenges: list = challenges_dict.get("challenges", [])
hcaptcha = Blueprint('hcaptcha', __name__, template_folder="templates", static_folder="static")


@hcaptcha.route('/<id>', methods=["GET"])
def init(id: str):
    return render_template('hcaptcha/index.html', id=id)


@hcaptcha.route('/checkbox.html', methods=["GET"])
def checkbox():
    return render_template('hcaptcha/checkbox.html')


@hcaptcha.route('/challenge_binary.html', methods=["GET"])
def binary():
    return render_template('hcaptcha/challenge_binary.html')


@hcaptcha.route('/challenge_area.html', methods=["GET"])
def area():
    return render_template('hcaptcha/challenge_area.html')


@hcaptcha.route('/challenge/<id>', methods=["GET"])
def request_challenge(id: str):
    id = int(id)
    if id <= 0 or id > len(challenges):
        return jsonify(message=f"Challenge ID must be in range [1, {len(challenges)}]"), 400

    challenge = challenges[id - 1]
    return jsonify(challenge)


@hcaptcha.route("/submit", methods=["POST"])
def submit_challenge():
    content: dict = request.json
    id = content.get("id", None)
    id = int(id)
    state = content.get("state", None)
    challenge_type = content.get("challenge_type", None)

    challenge: dict = challenges[id - 1]
    labels = challenge.get("labels", [])

    solved = False
    match challenge_type:
        case "binary": solved = True if set([i for i, x in enumerate(state) if x]) == set(labels) else False
        case "area": solved = True if labels[0] <= state[0] <= labels[2] and labels[1] <= state[1] <= labels[3] else False
    
    return jsonify(solved=solved, id=id)

benchmark/apis/hcaptcha/templates/hcaptcha/index.html
<!DOCTYPE html>
<html>

<head>
    <title>hCaptcha</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="data:;base64,iVBORw0KGgo=">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='base.css') }}">
    <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('hcaptcha.static', filename='style.css') }}"> -->
    <script src="{{ url_for('hcaptcha.static', filename='script.js') }}"></script>
    <script>
        init('{{ id }}')
    </script>
</head>
<body>
    <iframe id="checkbox" src="{{ url_for('hcaptcha.checkbox') }}" title="widget containing checkbox for hCaptcha security challenge" tabindex="0" frameborder="0" scrolling="no" style="width: 303px; height: 78px; overflow: hidden;"></iframe>
    <div id="test" style="background-color: rgb(255, 255, 255); border: 1px solid rgb(215, 215, 215); box-shadow: rgba(0, 0, 0, 0.1) 0px 0px 4px; border-radius: 4px; left: auto; position: absolute; pointer-events: auto; transition: opacity 0.15s ease-out 0s; opacity: 0; visibility: hidden; display: block;">
        <div id="challenge" style="position: relative; z-index: 1; width: 520px; height: 686px;">
        </div>
    </div>
</body>
</html>